### ISSUE TITLE
Generating Minimap 

### ISSUE THREAD

**Issue by Balatuc** [JereKuusela/BetterContinents#1]
I just updated to the newest version of Better Continents and now every 30seconds Better Continents starts to generate the minimap. This causes a stutter in the game, every 20-30 seconds as the mini map loads. This is on a dedicated server, but the issue is on the client side with this bepinex log below. 

[Info   : Unity Log] [BetterContinents] Generating minimap textures multi-threaded ...
[Info   :Expand World Size] Map generation finished (12 seconds).
[Info   : Unity Log] [BetterContinents] Finished generating minimap textures multi-threaded ...
[Info   :Expand World Size] Starting map generation.
[Info   : Unity Log] [BetterContinents] Generating minimap textures multi-threaded ...
[Info   :Expand World Size] Map generation finished (12 seconds).
[Info   : Unity Log] [BetterContinents] Finished generating minimap textures multi-threaded ...
[Info   :Expand World Size] Starting map generation.
[Info   : Unity Log] [BetterContinents] Generating minimap textures multi-threaded ...
[Info   :Expand World Size] Map generation finished (12 seconds).
[Info   : Unity Log] [BetterContinents] Finished generating minimap textures multi-threaded ...
[Info   :Expand World Size] Starting map generation.
[Info   : Unity Log] [BetterContinents] Generating minimap textures multi-threaded ...
[Info   :Expand World Size] Map generation finished (12 seconds).

**Comment by JereKuusela** [comment]
Should work now ok.
